### ISSUE TITLE
No extension exist for source:sqs

### ISSUE THREAD

**Issue by shreyu86** [siddhi-io/docker-siddhi#11]
**Description:**
Unable to add SQS extension for Siddhi 5.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Siddhi 5.0

**OS, DB, other environment details and versions:**  
Docker on Mac

**Steps to reproduce:**
Following the steps I placed the jar files for sqs extension and dependencies at `docker-files/siddhi-runner/alpine/siddhi-runner/files/lib` and built the image but when I run a siddhi app I get the following error:

```java
 at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:45)
        at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:345)
        at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:114)
        at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:373)
        at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:229)
        at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:66)
        at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:76)
        at io.siddhi.distribution.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:69)
        at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:92)
        ... 14 more
```

Is there something I am missing? snapshot of the files being added
![image](https://user-images.githubusercontent.com/311217/59455940-15ca4b00-8dca-11e9-813d-bf88a7bea388.png)

**Related Issues:**

**Comment by niveathika** [comment]
The compatible version of the siddhi-io-sqs with Siddhi 5.0 is siddhi-io-sqs-2.0.0

**Comment by shreyu86** [comment]
Thanks @niveathika is there a guide on how to compile the sqs extension to generate the latest jar? I couldn't find 2.0 jar on Maven repository since they are not released.

**Comment by niveathika** [comment]
@shreyu86 Please find the maven central link for siddhi-io-sqs-2.0.0 below,
http://maven.wso2.org/nexus/content/repositories/releases/org/wso2/extension/siddhi/io/sqs/siddhi-io-sqs/2.0.0/

**Comment by shreyu86** [comment]
Great , thanks a lot! I'll try this out.

**Comment by shreyu86** [comment]
I get an 404 for the link provided.

**Comment by niveathika** [comment]
Apologies, please find the public link here,
http://maven.wso2.org/nexus/content/groups/wso2-public/org/wso2/extension/siddhi/io/sqs/siddhi-io-sqs/2.0.0/
